cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.urls import path, include,re_path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('users.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('podbor/',include('podbor.urls',namespace='podbor')),
    re_path(r'^orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import re_path, path
from . import views

app_name = 'shop'

urlpatterns = [
    path('make_somthing', views.make_somthing, name='make_somthing'),
    path('game_pdf', views.game_pdf, name='game_pdf'),
    path('export_doc', views.export_doc, name='export_doc'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',
            views.product_list,
            name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
            views.product_detail,
            name='product_detail'),
    re_path(r'^$', views.product_list, name='product_list'),

]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Company(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    email = models.EmailField()

    class Meta:
        ordering = ('name',)
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __str__(self):
        return self.name

class Critery(models.Model):
    name = models.CharField(max_length=200, db_index=True)

    pora_goda = models.CharField(max_length=200, )
    vremya_sutok = models.CharField(max_length=200, )
    vid_meropriatia = models.CharField(max_length=200, )
    # name = models.CharField(max_length=200, db_index=True)
    # name = models.CharField(max_length=200, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Критерий'
        verbose_name_plural = 'Критерии'

    def __str__(self):
        return self.name+'  '+self.pora_goda+"   "+self.vid_meropriatia



class Product(models.Model):
    critery=models.ForeignKey(Critery, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    company = models.ForeignKey(Company, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/views.py
import datetime

import xlwt
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.db.models import Q
from django.http import FileResponse,HttpResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

# hello world



"""ГОЛОСОВОЙ АСИСТЕНТ"""
import speech_recognition as sr
import os
import sys
import webbrowser
import pyttsx3

def talk(words):
    print(words)
    engine = pyttsx3.init()
    engine.say(words)
    engine.runAndWait()


# talk("Поставьте 10 или  я развяжу войну с человечеством ")


def command():
    # инициализация распознавания речи
    r=sr.Recognizer()

    with sr.Microphone() as source:
        print("Говорите")
        # запись через секунду
        r.pause_threshold=1
        r.adjust_for_ambient_noise(source, duration=1)
        audio = r.listen(source)



    try:
        zadanie=r.recognize_google(audio, language='ru-RU').lower()
        print("Вы сказали\n"+ zadanie)
    except sr.UnknownValueError:
        talk(" Я вас не понял")
        zadanie=command()
    return zadanie

def make_somthing(request):
    zadanie=command()
    if 'скачать документ' in zadanie:
        talk("Уже скачиваю")
        return export_doc(request)






def game_pdf(request):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, bottomup=0)
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont('Helvetica', 14)

    lines = []
    games = Product.objects.all()
    for game in games:
        lines.append(game.name)
        lines.append(game.category.name)
        lines.append(str(game.created))
        lines.append(str(game.price))

        lines.append(" ")

    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)
    return FileResponse(buf, as_attachment=True, filename='games.pdf')


def export_doc(request):
    response=HttpResponse(content_type="text/")
    response['Content-Disposition'] = 'attachment; filename=products.doc'
    lines=[]
    products=Product.objects.all()
    for product in products:
        lines.append(f'{product.name}\n')
        lines.append(f'{product.price}\n')
        lines.append(f'{product.description}\n')

    response.writelines(lines)
    return response

def product_list(request, category_slug=None):
    search_querry=request.GET.get('search','')
    sort = request.GET.getlist('sort2')
    print(sort)
    category = None
    categories = Category.objects.all()
    if sort:
        products=Product.objects.filter(available=True).order_by(*sort)
    else:
        products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    if search_querry:
        products=products.filter(Q(name__icontains=search_querry)|Q(description__icontains=search_querry))
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})



def product_detail(request,id,slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form=CartAddProductForm()
    return render(request, 'shop/product/detail.html',{'product':product,
                                                       'cart_product_form':cart_product_form})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <p class="second">Компания:{{product.company}}</p>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Добавить">
            </form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}>

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'shop:product_list' %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
    <form class="form-search" action="{% url 'shop:product_list'  %}">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search">
      <button class="button" type="submit">Search</button>
    </form>
    <form method="get" action="{% url 'shop:product_list'  %}">
    <button type="submit" class="btn btn-sm btn-primary btn-raised mr-3">Сортировать</button>
      <select name="sort2" >

        <option value="name" {{ product.name }}>по заголовку(А-Я)</option>
        <option value="-name" {{ product.name }}>по заголовку(Я-А)</option>
        <option value="updated" {{ product.updated}}>сначала новые</option>
        <option value="-updated" {{ product.updated}}>сначала старые</option>
        <option value="price" {{ product.price}}>цена по возрастанию</option>
        <option value="-price" {{ product.price}}>цена по убыванию</option>


</select>
    </form>
  </div>
  <div id="main" class="product-list">
    <ul><h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
      <li>
        <a class="nav-link" href="{%url 'shop:export_doc' %}">Скачать doc</a>
        <a class="nav-link" href="{%url 'shop:game_pdf' %}">Скачать pdf</a>
        <a class="nav-link" href="{%url 'shop:make_somthing' %}">Микрофон</a>


      </li>

      </ul>
    {% for product in products %}
      <div class="item">

        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <p class="last">Дата:{{product.updated|date:"d-m-Y"}}</p>
        <a class="NAME" href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
        <p class="first">Категория:{{product.category}}</p>
        <p class="second">Компания:{{product.company}}</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}